spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/res1
    password: 123
    username: postgres

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update



    properties:
      hibernate:
        globally_quoted_identifiers: true

token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855




